//! `POST /send` - operator-only. Auth via `Authorization: Bearer ...`
//! matching `config.send_auth_token`. Body is JSON `{send_id, subject,
//! markdown}`.
//!
//! Walks the `Active` subscribers partition, mints a per-recipient
//! unsubscribe token, sends via the configured relay, and records one
//! [`crate::store::Delivery`] ledger row per recipient — whatever the
//! outcome. `send_id` is caller-supplied, not minted here: see
//! [`resolve_send`] for why that is what makes a retry idempotent.

use axum::extract::{Request, State};
use lettre::Message;
use lettre::message::Mailbox;
use lettre::message::header::{ContentType, HeaderName, HeaderValue};
use pulldown_cmark::{Options, Parser, html};
use secrecy::ExposeSecret;
use serde::{Deserialize, Serialize};
use time::OffsetDateTime;

use crate::AppState;
use crate::config::Config;
use crate::error::{Error, Result};
use crate::handlers::check_bearer;
use crate::send_id::SendId;
use crate::store::{Delivery, DeliveryStatus, Send};
use crate::templates;
use crate::token::{Token, TokenKind, sign};

/// Hard cap on `/send` request bodies. Mirrors the router-level
/// `RequestBodyLimitLayer` so the body collector here can't be tricked
/// by a stripped layer.
const SEND_BODY_LIMIT_BYTES: usize = 256 * 1024;

/// Hard cap on the stored `subject`, in bytes.
///
/// WHY: the subject is persisted verbatim and rendered into the archive
/// index, the detail page `<h1>` and the `<title>`, so without a bound
/// one send decides the size of every page it appears on — and the body
/// limit alone permits a 256 KiB subject. 200 bytes sits well above the
/// 78-character subject line RFC 5322 recommends and far below its
/// 998-octet hard limit, so no realistic newsletter subject is refused.
const MAX_SUBJECT_LEN: usize = 200;

/// How long a per-recipient unsubscribe link stays valid. Deliberately
/// generous (unlike the 24h confirm-link TTL): an unsubscribe link is
/// embedded in a specific sent email a recipient may reopen months
/// later, and a token that has quietly expired by then leaves them
/// unable to opt out from that link — the opposite of what an
/// unsubscribe mechanism exists for. Revocation is handled by the
/// consent-generation check (forkwright/epistole#65), not by expiry:
/// any later consent event for that address still invalidates the
/// token immediately, regardless of this TTL.
const UNSUBSCRIBE_LINK_TTL: time::Duration = time::Duration::days(3650);

/// Request body for `POST /send`.
#[derive(Debug, Deserialize)]
pub(crate) struct Body {
    /// Caller-supplied idempotency key. NOT generated by this handler —
    /// see [`resolve_send`] for why that is load-bearing.
    pub(crate) send_id: SendId,
    pub(crate) subject: String,
    pub(crate) markdown: String,
}

/// Reply payload for `POST /send`.
#[derive(Debug, Serialize)]
pub(crate) struct Reply {
    pub(crate) send_id: SendId,
    /// Recipients this call sent to (relay accepted).
    pub(crate) sent: usize,
    /// Recipients this call attempted but the relay rejected.
    pub(crate) failed: usize,
    /// Recipients skipped because a delivery row for this `send_id`
    /// already existed — the idempotency path. On a fresh `send_id`
    /// this is always 0.
    pub(crate) already_delivered: usize,
    /// Recipients not attempted this call because the hourly or daily
    /// send cap was reached. Retry the same `send_id` once the window
    /// rolls over to pick these up — the skip above means already-sent
    /// recipients are not re-sent.
    pub(crate) deferred_by_cap: usize,
}

/// Handle `POST /send`. The body extractor is intentionally NOT in the
/// signature: we authenticate first, then read and parse the body —
/// otherwise a flood of unauthenticated 256 KiB POSTs would each cost
/// the service one full JSON parse before the bearer check fired.
///
/// # Errors
///
/// Returns [`Error::Unauthorized`] when the bearer token is missing or
/// wrong, [`Error::BadRequest`] on an oversized body, an empty subject,
/// a subject over [`MAX_SUBJECT_LEN`] bytes, malformed JSON, missing
/// markdown, or a `send_id` already used for different content,
/// [`Error::Store`] on a fjall failure, [`Error::Config`] if token
/// signing cannot be initialized. A per-recipient relay or composition
/// failure does NOT fail this call — see [`build_message`] — it is
/// recorded as a `Failed` delivery and reflected in the reply's `failed`
/// count instead.
pub(crate) async fn post(
    State(state): State<AppState>,
    request: Request,
) -> Result<axum::Json<Reply>> {
    // 1. Auth FIRST. Unauthenticated requests pay no body-collect or
    //    JSON-parse cost.
    if !check_bearer(
        request.headers(),
        state.config.send_auth_token.expose_secret(),
    ) {
        return Err(Error::Unauthorized);
    }

    // 2. Collect body with a hard cap. The router-level body limit also
    //    enforces this, but a defense-in-depth re-check inside the
    //    handler protects us if the layer is ever moved.
    let body_bytes = axum::body::to_bytes(request.into_body(), SEND_BODY_LIMIT_BYTES)
        .await
        .map_err(|e| Error::BadRequest {
            reason: format!("read body: {e}"),
        })?;

    // 3. Parse JSON.
    let body: Body = serde_json::from_slice(&body_bytes).map_err(|e| Error::BadRequest {
        reason: format!("parse JSON: {e}"),
    })?;

    if body.subject.trim().is_empty() {
        return Err(Error::BadRequest {
            reason: "subject is empty".to_owned(),
        });
    }
    // WHY: measured on the value actually stored, not the trimmed one, so
    // the bound covers exactly what the archive pages will render.
    if body.subject.len() > MAX_SUBJECT_LEN {
        return Err(Error::BadRequest {
            reason: format!("subject exceeds {MAX_SUBJECT_LEN} bytes"),
        });
    }
    if body.markdown.trim().is_empty() {
        return Err(Error::BadRequest {
            reason: "markdown body is empty".to_owned(),
        });
    }

    // 4. Render markdown to HTML, then sanitize. pulldown-cmark by
    //    default strips raw HTML blocks but it preserves URLs verbatim
    //    in markdown links (`[click](javascript:alert(1))` becomes
    //    `<a href="javascript:alert(1)">`). ammonia's default URL-scheme
    //    allowlist is conservative (http/https/mailto/etc.) — javascript:
    //    and data: are dropped.
    let mut html_raw = String::new();
    let parser = Parser::new_ext(
        &body.markdown,
        Options::ENABLE_TABLES | Options::ENABLE_STRIKETHROUGH,
    );
    html::push_html(&mut html_raw, parser);
    let html_out = ammonia::clean(&html_raw);

    let now = OffsetDateTime::now_utc();
    let send_rec = resolve_send(&state, body.send_id, &body.subject, &html_out, now)?;

    let active = state.store.active_subscribers()?;
    let hour_bucket = hour_bucket(now);
    let day_bucket = day_bucket(now);

    let mut sent = 0usize;
    let mut failed = 0usize;
    let mut already_delivered = 0usize;
    let mut deferred_by_cap = 0usize;

    for subscriber in &active {
        // Per-recipient idempotency: a retry of this exact send_id must
        // not re-send (or re-record) a recipient it already reached.
        if state
            .store
            .delivery_get(&send_rec.id, &subscriber.email)?
            .is_some()
        {
            already_delivered += 1;
            continue;
        }

        let admitted = state
            .store
            .try_reserve_send_slot(
                &hour_bucket,
                &day_bucket,
                state.config.send_cap_per_hour,
                state.config.send_cap_per_day,
            )
            .await?;
        if !admitted {
            deferred_by_cap += 1;
            continue;
        }

        let exp_unix = now.unix_timestamp() + UNSUBSCRIBE_LINK_TTL.whole_seconds();
        let token = Token::new(
            TokenKind::Unsubscribe,
            subscriber.email.clone(),
            exp_unix,
            subscriber.generation,
        );
        let signed = sign(&token, state.config.token_secret.expose_secret().as_bytes())?;
        let unsubscribe_url = format!("{}/unsubscribe?token={signed}", state.config.base_url);
        let one_click_url = format!(
            "{}/unsubscribe/one-click?token={signed}",
            state.config.base_url
        );

        let message = build_message(
            &state.config,
            &send_rec,
            &subscriber.email,
            &unsubscribe_url,
            &one_click_url,
        );
        let (status, error) = match message {
            Ok(message) => match state.mailer.send(message).await {
                Ok(()) => (DeliveryStatus::Sent, None),
                Err(e) => (DeliveryStatus::Failed, Some(e.to_string())),
            },
            Err(e) => (DeliveryStatus::Failed, Some(e.to_string())),
        };

        state.store.delivery_put(&Delivery {
            send_id: send_rec.id,
            email: subscriber.email.clone(),
            status,
            at: OffsetDateTime::now_utc(),
            error,
        })?;

        match status {
            DeliveryStatus::Sent => sent += 1,
            _ => failed += 1,
        }
    }

    tracing::info!(
        send_id = %send_rec.id,
        sent,
        failed,
        already_delivered,
        deferred_by_cap,
        "send fan-out complete"
    );

    Ok(axum::Json(Reply {
        send_id: send_rec.id,
        sent,
        failed,
        already_delivered,
        deferred_by_cap,
    }))
}

/// UTC-hour rate-limit bucket key, e.g. `2026081518` — matches
/// [`crate::store::Store::try_reserve_send_slot`]'s bucket-string
/// contract. Fixed-width manual formatting, same approach `templates.rs`
/// already uses for `OffsetDateTime` — sidesteps pulling in the
/// `format_description` machinery for two integers.
fn hour_bucket(at: OffsetDateTime) -> String {
    format!(
        "{:04}{:02}{:02}{:02}",
        at.year(),
        u8::from(at.month()),
        at.day(),
        at.hour()
    )
}

/// UTC-day rate-limit bucket key, e.g. `20260815`.
fn day_bucket(at: OffsetDateTime) -> String {
    format!("{:04}{:02}{:02}", at.year(), u8::from(at.month()), at.day())
}

/// Resolve the [`Send`] record for `send_id`, creating it if this is the
/// first call.
///
/// This is the whole idempotency mechanism's anchor: `send_id` arrives
/// as caller INPUT (the `Body::send_id` field), not something this
/// handler mints. A client that retries a failed or ambiguous request
/// (timeout, connection reset) resubmits the identical `send_id`, so the
/// second call lands here and finds the record [`resolve_send`] already
/// wrote on the first — it reuses that record rather than creating a
/// second `Send` (which would then fan out to every recipient a second
/// time). Content that doesn't match is refused rather than silently
/// preferring either version, since a caller sending "the same id, new
/// subject" almost certainly minted a fresh campaign and reused an id by
/// mistake — the write that actually MOVED mail (the fan-out below) must
/// never proceed under an ambiguous idea of what content that was.
///
/// # Errors
///
/// Returns [`Error::Store`] on a fjall failure, [`Error::BadRequest`]
/// when `send_id` already names a `Send` with different subject or body.
fn resolve_send(
    state: &AppState,
    send_id: SendId,
    subject: &str,
    body_html: &str,
    now: OffsetDateTime,
) -> Result<Send> {
    if let Some(existing) = state.store.send_get(&send_id)? {
        if existing.subject != subject || existing.body_html != body_html {
            return Err(Error::BadRequest {
                reason: format!(
                    "send_id {send_id} was already recorded with different content — reuse a \
                     send_id only to retry the SAME send, mint a fresh one for a new campaign"
                ),
            });
        }
        return Ok(existing);
    }

    let send_rec = Send {
        id: send_id,
        subject: subject.to_owned(),
        body_html: body_html.to_owned(),
        sent_at: now,
    };
    // The reply hands `send_id` back to the operator, so the record is
    // durable before fan-out starts — `send_put` fsyncs the journal.
    state.store.send_put(&send_rec)?;
    Ok(send_rec)
}

/// Compose the outbound `Message` for one recipient of `send`.
///
/// Sets `List-Unsubscribe` / `List-Unsubscribe-Post` per RFC 8058,
/// pointed at the one-click endpoint per DEPLOY.md's documented contract
/// — a mail client's own "unsubscribe" affordance can complete the
/// action with a single POST, no interstitial. The human-facing link in
/// the body goes to the GET/interstitial flow instead, since a visitor
/// clicking a link in their mail client expects a page, not a silent
/// POST.
///
/// # Errors
///
/// Returns [`Error::Smtp`] when the brand's `from_address`/`reply_to`,
/// or the recipient's own address, fail to parse as an RFC 5322 mailbox,
/// or when message composition otherwise fails.
fn build_message(
    config: &Config,
    send: &Send,
    to_email: &str,
    unsubscribe_url: &str,
    one_click_url: &str,
) -> Result<Message> {
    let from: Mailbox = format!("{} <{}>", config.brand.name, config.brand.from_address)
        .parse()
        .map_err(|e| Error::Smtp {
            reason: format!("brand from_address: {e}"),
        })?;
    let to: Mailbox = to_email.parse().map_err(|e| Error::Smtp {
        reason: format!("recipient address: {e}"),
    })?;

    let mut builder = Message::builder()
        .from(from)
        .to(to)
        .subject(send.subject.clone());

    if let Some(reply_to) = &config.brand.reply_to {
        let reply: Mailbox = reply_to.parse().map_err(|e| Error::Smtp {
            reason: format!("brand reply_to: {e}"),
        })?;
        builder = builder.reply_to(reply);
    }

    builder = builder
        .header(ContentType::TEXT_HTML)
        .raw_header(HeaderValue::new(
            HeaderName::new_from_ascii_str("List-Unsubscribe"),
            format!("<{one_click_url}>"),
        ))
        .raw_header(HeaderValue::new(
            HeaderName::new_from_ascii_str("List-Unsubscribe-Post"),
            "List-Unsubscribe=One-Click".to_owned(),
        ));

    let html_body = templates::newsletter_email_html(&send.body_html, unsubscribe_url);
    builder.body(html_body).map_err(|e| Error::Smtp {
        reason: format!("compose message: {e}"),
    })
}
